server:
  port: 8080

spring:
  datasource:
    name: ruoyi
    url: jdbc:mysql://localhost:3306/ruoyi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ruoyi
    password: 123456
    driverClassName:  com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/**/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.springboot.entity  # 注意：对应实体类的路径
    # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml